version: "3.7"
services:
  vite_docker:
    image: cms_frontend_image
    container_name: cms_frontend_container
    build: .
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    # working_dir: /srv/app
    volumes:
      - .:/app
    tty: true
